/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.PessoaVO;
import servicos.PessoaServicos;
import utilidades.GeraPDF;

/**
 *
 * @author Fernando & João Vitor
 * @since 12/06/2017
 * @version Beta Xamego 1.9
 */
public class GUICadPessoa extends javax.swing.JInternalFrame {
    
    PessoaVO pVO = new PessoaVO();

    /* Criando um modelo de tabela padrão 
     com o nome das colunas */
    DefaultTableModel dtm = new DefaultTableModel(
            new Object[][]{},
            new Object[]{"Código", "Nome", "CPF", "Endereco", "Bairro", "Numero", "Complemento",
                                "CEP", "Telefone", "Observacao", "UF", "Cidade" });

    
    /**
     * Creates new form Cadastro
     */
    public GUICadPessoa() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlCodigo = new javax.swing.JLabel();
        jlNome = new javax.swing.JLabel();
        jlCPF = new javax.swing.JLabel();
        jtId = new javax.swing.JTextField();
        jtNome = new javax.swing.JTextField();
        jtCPF = new javax.swing.JTextField();
        jRua = new javax.swing.JLabel();
        jlBairro = new javax.swing.JLabel();
        jlCEP = new javax.swing.JLabel();
        jlTelefone = new javax.swing.JLabel();
        jtRua = new javax.swing.JTextField();
        jtBairro = new javax.swing.JTextField();
        jtCEP = new javax.swing.JTextField();
        jtTelefone = new javax.swing.JTextField();
        jlCidade = new javax.swing.JLabel();
        jtCidade = new javax.swing.JTextField();
        jtNumero = new javax.swing.JTextField();
        jtComplemento = new javax.swing.JTextField();
        jlNumero = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jbCadastro = new javax.swing.JButton();
        jbLimpar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Cadastro");

        jlCodigo.setText("Código:");

        jlNome.setText("Nome:");

        jlCPF.setText("CPF/CNPJ:");

        jtId.setEnabled(false);

        jtNome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtNomeFocusLost(evt);
            }
        });

        jtCPF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtCPFFocusLost(evt);
            }
        });

        jRua.setText("Endereço:");

        jlBairro.setText("Bairro:");

        jlCEP.setText("CEP:");

        jlTelefone.setText("Telefone:");

        jtRua.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtRuaFocusLost(evt);
            }
        });

        jtBairro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtBairroFocusLost(evt);
            }
        });

        jtCEP.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtCEPFocusLost(evt);
            }
        });

        jtTelefone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtTelefoneFocusLost(evt);
            }
        });

        jlCidade.setText("Cidade:");

        jtCidade.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtCidadeFocusLost(evt);
            }
        });

        jtNumero.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtNumeroFocusLost(evt);
            }
        });

        jtComplemento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtComplementoFocusLost(evt);
            }
        });

        jlNumero.setText("Numero:");

        jLabel12.setText("Complemento:");

        jbCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/+.fw.png"))); // NOI18N
        jbCadastro.setContentAreaFilled(false);
        jbCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadastroActionPerformed(evt);
            }
        });

        jbLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/l.fw.png"))); // NOI18N
        jbLimpar.setContentAreaFilled(false);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/pdf.fw.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jtCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jlCidade))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jlTelefone)
                                        .addComponent(jtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jtRua, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jlNumero)
                                        .addComponent(jtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGap(18, 18, 18)
                            .addComponent(jtComplemento))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jlCodigo)
                                .addComponent(jtId, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jRua))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(191, 191, 191)
                                    .addComponent(jlBairro))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(22, 22, 22)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jlNome)
                                        .addComponent(jtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jlCPF)
                                        .addComponent(jtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(229, 229, 229)
                                    .addComponent(jLabel12))))
                        .addComponent(jlCEP))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlCodigo)
                    .addComponent(jlNome)
                    .addComponent(jlCPF))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRua)
                    .addComponent(jlBairro)
                    .addComponent(jlNumero)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlCEP)
                    .addComponent(jlCidade)
                    .addComponent(jlTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jbLimpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbCadastro))
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadastroActionPerformed
        cadastrar();
        limparp();
    }//GEN-LAST:event_jbCadastroActionPerformed

    private void jtNomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtNomeFocusLost
        if(jtNome.getText().isEmpty()){
            jtNome.setBackground(Color.decode("#f98000"));
        }else{
            jtNome.setBackground(Color.white);
            jtNome.setForeground(Color.green);
        }
    }//GEN-LAST:event_jtNomeFocusLost

    private void jtCPFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtCPFFocusLost
        if(jtCPF.getText().isEmpty()){
            jtCPF.setBackground(Color.decode("#f98000"));
        }else{
            jtCPF.setBackground(Color.white);
            jtCPF.setForeground(Color.green);
        }
    }//GEN-LAST:event_jtCPFFocusLost

    private void jtRuaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtRuaFocusLost
        if(jtRua.getText().isEmpty()){
            jtRua.setBackground(Color.decode("#f98000"));
        }else{
            jtRua.setBackground(Color.white);
            jtRua.setForeground(Color.green);
        }
    }//GEN-LAST:event_jtRuaFocusLost

    private void jtBairroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtBairroFocusLost
        if(jtBairro.getText().isEmpty()){
            jtBairro.setBackground(Color.decode("#f98000"));
        }else{
            jtBairro.setBackground(Color.white);
            jtBairro.setForeground(Color.green);
        }
    }//GEN-LAST:event_jtBairroFocusLost

    private void jtNumeroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtNumeroFocusLost
        if(jtNumero.getText().isEmpty()){
            jtNumero.setBackground(Color.decode("#f98000"));
        }else{
            jtNumero.setBackground(Color.white);
            jtNumero.setForeground(Color.green);
        }
    }//GEN-LAST:event_jtNumeroFocusLost

    private void jtComplementoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtComplementoFocusLost
        if(jtComplemento.getText().isEmpty()){
            jtComplemento.setBackground(Color.decode("#f98000"));
        }else{
            jtComplemento.setBackground(Color.white);
            jtComplemento.setForeground(Color.green);
        }
    }//GEN-LAST:event_jtComplementoFocusLost

    private void jtCEPFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtCEPFocusLost
        if(jtCEP.getText().isEmpty()){
            jtCEP.setBackground(Color.decode("#f98000"));
        }else{
            jtCEP.setBackground(Color.white);
            jtCEP.setForeground(Color.green);
        }
    }//GEN-LAST:event_jtCEPFocusLost

    private void jtCidadeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtCidadeFocusLost
        if(jtCidade.getText().isEmpty()){
            jtCidade.setBackground(Color.decode("#f98000"));
        }else{
            jtCidade.setBackground(Color.white);
            jtCidade.setForeground(Color.green);
        }
    }//GEN-LAST:event_jtCidadeFocusLost

    private void jtTelefoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtTelefoneFocusLost
        if(jtTelefone.getText().isEmpty()){
            jtTelefone.setBackground(Color.decode("#f98000"));
        }else{
            jtTelefone.setBackground(Color.white);
            jtTelefone.setForeground(Color.green);
        }
    }//GEN-LAST:event_jtTelefoneFocusLost

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       gerarPDF();
       receberDados();
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void cadastrar() {
        try {
            
            pVO.setNome(jtNome.getText());
            pVO.setCpf(jtCPF.getText());
            pVO.setEndereco(jtRua.getText());
            pVO.setBairro(jtBairro.getText());
            pVO.setNumero(Integer.parseInt(jtNumero.getText()));
            pVO.setComplemento(jtComplemento.getText());
            pVO.setCep(Integer.parseInt(jtCEP.getText()));
            pVO.setTelefone(jtTelefone.getText());
            pVO.setCidade(jtCidade.getText());
            
            
            /* Aqui você deve colocar o código para 
             * inserir o objeto no banco de dados */
            PessoaServicos ps = servicos.servicosFactory.getPessoaServicos();
            ps.cadastarPessoa(pVO);//aq ele envia pra cadastrar no banco 

             //Criando um ArrayList<ProdutoVO> vazio
             //para receber o ArrayList com os dados 
             ArrayList<PessoaVO> prod = new ArrayList<>();

            //Recebendo o ArrayList cheio em produtos
            prod = ps.buscarPessoas();

            for (int i = 0; i < prod.size(); i++) {
                dtm.addRow(new String[]{
                    String.valueOf(prod.get(i).getCod_cli()),
                    String.valueOf(prod.get(i).getNome()),
                    String.valueOf(prod.get(i).getCpf()),
                    String.valueOf(prod.get(i).getEndereco()),
                    String.valueOf(prod.get(i).getBairro()),
                    String.valueOf(prod.get(i).getNumero()),
                    String.valueOf(prod.get(i).getComplemento()),
                    String.valueOf(prod.get(i).getCep()),
                    String.valueOf(prod.get(i).getTelefone()),
                    String.valueOf(prod.get(i).getCidade()),
                });
            }//fecha */
            JOptionPane.showMessageDialog(rootPane,"Você foi cadastrada com sucesso!");
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane,"Erro! "+e.getMessage(),"erro",JOptionPane.ERROR_MESSAGE);
        }//fecha catch
    }
    private void receberDados() {
        try {

            pVO.setNome(jtNome.getText());
            pVO.setCpf(jtCPF.getText());
            pVO.setEndereco(jtRua.getText());
            pVO.setBairro(jtBairro.getText());
            pVO.setNumero(Integer.parseInt(jtNumero.getText()));
            pVO.setComplemento(jtComplemento.getText());
            pVO.setCep(Integer.parseInt(jtCEP.getText()));
            pVO.setTelefone(jtTelefone.getText());
            pVO.setCidade(jtCidade.getText());
            
         
            JOptionPane.showMessageDialog(
                    this,
                    "Dados cadastrados com sucesso!"
                  + "\n"+pVO.toString());

        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                    this,
                    "Erro! " + e.getMessage());
        }//fecha catch

    }//fecha método
    public void gerarPDF(){
        try {
             /* Também podemos pedir para o usuário o nome que ele deseja colocar
               no arquivo PDF através de um JOptionPane.showInputDialog */
            String nomePDF = JOptionPane.showInputDialog(this, 
                                    "Digite o nome que deseja para o arquivo de PDF");
            
            //Opcional, método que altera o nome do PDF.
            GeraPDF.setNomePDF(nomePDF);
            //GeraPDF.setNomePDF("arquivo1"); Nome fixo

            //Método que gera um arquivo PDF.
            GeraPDF.gerarPDF(pVO);
            
            
            JOptionPane.showMessageDialog(this, 
                    "PDF gerado com sucesso!"
                  + "\nNome do arquivo gerado: "+nomePDF);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Erro! " + e.getMessage());
        }//fecha catch
    
    }//fecha método
    private void limparp(){
        
        jtNome.setText("");
        jtCPF.setText("");
        jtRua.setText("");
        jtBairro.setText("");
        jtNumero.setText("");
        jtComplemento.setText("");
        jtCEP.setText("");
        jtTelefone.setText("");
        jtCidade.setText("");
    }//fecha método limpar
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jRua;
    private javax.swing.JButton jbCadastro;
    private javax.swing.JButton jbLimpar;
    private javax.swing.JLabel jlBairro;
    private javax.swing.JLabel jlCEP;
    private javax.swing.JLabel jlCPF;
    private javax.swing.JLabel jlCidade;
    private javax.swing.JLabel jlCodigo;
    private javax.swing.JLabel jlNome;
    private javax.swing.JLabel jlNumero;
    private javax.swing.JLabel jlTelefone;
    private javax.swing.JTextField jtBairro;
    private javax.swing.JTextField jtCEP;
    private javax.swing.JTextField jtCPF;
    private javax.swing.JTextField jtCidade;
    private javax.swing.JTextField jtComplemento;
    private javax.swing.JTextField jtId;
    private javax.swing.JTextField jtNome;
    private javax.swing.JTextField jtNumero;
    private javax.swing.JTextField jtRua;
    private javax.swing.JTextField jtTelefone;
    // End of variables declaration//GEN-END:variables
}
