/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.PessoaVO;
import servicos.PessoaServicos;
import servicos.servicosFactory;

/**
 *
 * @author Fernando & João Vitor
 * @since 12/06/2017
 * @version Beta Xamego 1.9
 */
public class GUIManutencaoProduto extends javax.swing.JInternalFrame {

    DefaultTableModel p = new DefaultTableModel(
        new Object[][]{},
        new Object[]{"cod_pro","produto","valor","quantidade_estoque"}        
    );
    
    /**
     * Creates new form GUIManutencaoProduto
     */
    public GUIManutencaoProduto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbDeletar = new javax.swing.JButton();
        jbLimpar = new javax.swing.JButton();
        jbPreencher = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabelaProduto = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox<>();
        jtPesquisar = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Manutenção de Produto");

        jbDeletar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/d.fw.png"))); // NOI18N
        jbDeletar.setContentAreaFilled(false);
        jbDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDeletarActionPerformed(evt);
            }
        });

        jbLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/l.fw.png"))); // NOI18N
        jbLimpar.setContentAreaFilled(false);
        jbLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparActionPerformed(evt);
            }
        });

        jbPreencher.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/p.fw.png"))); // NOI18N
        jbPreencher.setContentAreaFilled(false);
        jbPreencher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPreencherActionPerformed(evt);
            }
        });

        jTabelaProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTabelaProduto);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "codigo", "produto", "valor", "quantidade_estoque" }));

        jtPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtPesquisarKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtPesquisarKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbPreencher, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 49, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbPreencher, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jbLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jbDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void atualizarTabelaPro(){
        try {
            ArrayList<PessoaVO> prods = new ArrayList<>();
            
            
            PessoaServicos ps = servicosFactory.getPessoaServicos();
            
            prods = ps.buscarProduto();
            
            for(int i = 0 ; i < prods.size() ; i++){
                p.addRow(new String[]{
                String.valueOf(prods.get(i).getCod_pro()),
                String.valueOf(prods.get(i).getProduto()),
                String.valueOf(prods.get(i).getValor()),
                String.valueOf(prods.get(i).getQuantidadeEstoque()),
                 });
        }//fecha for
        
            jTabelaProduto.setModel(p);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Erro! "+e.getMessage());
        }
    }//fecha atualizar
    
    private void deleta(){
        try {
            int linha = jTabelaProduto.getSelectedRow();
            
            if(linha == -1){
                JOptionPane.showMessageDialog(rootPane,"selecione uma linha para exclusão, por favor!");
            }else{
                String id = jTabelaProduto.getValueAt(linha, 0).toString();
                
                PessoaServicos ps =servicosFactory.getPessoaServicos();
                ps.deleteProduto(Long.parseLong(id));
                
                JOptionPane.showMessageDialog(rootPane, "produto excluido com sucesso!");
            }//fecha else
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "errou! "+e.getMessage());
        }//fecha cath
    }//fecha deletar
    
    private void procura(){
         try {
            if(jtPesquisar.getText().isEmpty()){
                atualizarTabelaPro();
            }else{
                String filtro = jComboBox1.getSelectedItem().toString();
                String query="";
                if(filtro.equalsIgnoreCase("codigo")){
                    query="where cod_pro = "+jtPesquisar.getText();
                }else if(filtro.equalsIgnoreCase("produto")){
                   query="where produto like '%"+jtPesquisar.getText()+"%'";     
                }else if(filtro.equalsIgnoreCase("Valor")){
                    query="where valor like '%"+jtPesquisar.getText()+"%'";
                }else if(filtro.equalsIgnoreCase("Quantidade_estoque")){
                    query="where quantidade_estoque = "+jtPesquisar.getText();
                    
                }//fecha else if

                PessoaServicos ps =servicosFactory.getPessoaServicos();
                ArrayList<PessoaVO> pro = new ArrayList<>();
                
                pro = ps.filtrarPro(query);//envia a consulta
                
                for (int i = 0; i < pro.size(); i++) {
                    p.addRow(new String[]{
                        String.valueOf(pro.get(i).getCod_pro()),
                        String.valueOf(pro.get(i).getProduto()),
                        String.valueOf(pro.get(i).getValor()),
                        String.valueOf(pro.get(i).getQuantidadeEstoque())
                });
            }//fecha for
            
            jTabelaProduto.setModel(p);
    
            }//fecha else
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane,"Erro"+e.getMessage());
        }
    }//fecha procurar
    
    private void limpar(){
        p.setNumRows(0);
    }//fecha limpar
    
    private void jbPreencherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPreencherActionPerformed
        limpar();
        atualizarTabelaPro();
    }//GEN-LAST:event_jbPreencherActionPerformed

    private void jbLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparActionPerformed
        limpar();
    }//GEN-LAST:event_jbLimparActionPerformed

    private void jbDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDeletarActionPerformed
        deleta();
        limpar();
        procura();
    }//GEN-LAST:event_jbDeletarActionPerformed

    private void jtPesquisarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtPesquisarKeyPressed
        limpar();
        procura();
    }//GEN-LAST:event_jtPesquisarKeyPressed

    private void jtPesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtPesquisarKeyReleased
        limpar();
        procura();
    }//GEN-LAST:event_jtPesquisarKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTabelaProduto;
    private javax.swing.JButton jbDeletar;
    private javax.swing.JButton jbLimpar;
    private javax.swing.JButton jbPreencher;
    private javax.swing.JTextField jtPesquisar;
    // End of variables declaration//GEN-END:variables
}
