/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.PessoaVO;
import servicos.PessoaServicos;
import servicos.servicosFactory;

/**
 *
 * @author Fernando & João Vitor
 * @since 12/06/2017
 * @version Beta Xamego 1.9
 */
public class GUIManutencaoPessoa extends javax.swing.JInternalFrame {

    DefaultTableModel pe = new DefaultTableModel(
        new Object[][]{},
        new Object[]{"cod_cli","Nome","cpf","endereco","bairro"
                    ,"numero","complemento","cep","telefone","cidade"}        
    );
    
    /**
     * Creates new form GUIManuPessoa
     */
    public GUIManutencaoPessoa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbLimparTP = new javax.swing.JButton();
        jbPreencherTP = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtablePessoa = new javax.swing.JTable();
        jtPesquisarP = new javax.swing.JTextField();
        jComboCli = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Manutenção de Pessoa");

        jbLimparTP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/l.fw.png"))); // NOI18N
        jbLimparTP.setContentAreaFilled(false);
        jbLimparTP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparTPActionPerformed(evt);
            }
        });

        jbPreencherTP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/p.fw.png"))); // NOI18N
        jbPreencherTP.setContentAreaFilled(false);
        jbPreencherTP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPreencherTPActionPerformed(evt);
            }
        });

        jtablePessoa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtablePessoa);

        jtPesquisarP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtPesquisarPKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtPesquisarPKeyReleased(evt);
            }
        });

        jComboCli.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "cod_cli", "Nome", "cpf", "endereco", "bairro", "numero", "complemento", "cep", "telefone", "cidade" }));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/d.fw.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 599, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbPreencherTP, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbLimparTP, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jtPesquisarP, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboCli, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtPesquisarP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbLimparTP, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbPreencherTP, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void atualizar(){
        try {
            ArrayList<PessoaVO> prods = new ArrayList<>();
            
            
            PessoaServicos ps = servicosFactory.getPessoaServicos();
            
            prods = ps.buscarPessoas();
            
            for(int i = 0 ; i < prods.size() ; i++){
                pe.addRow(new String[]{
                String.valueOf(prods.get(i).getCod_cli()),
                prods.get(i).getNome(),
                String.valueOf(prods.get(i).getCpf()),
                String.valueOf(prods.get(i).getEndereco()),
                String.valueOf(prods.get(i).getBairro()),
                String.valueOf(prods.get(i).getNumero()),
                String.valueOf(prods.get(i).getComplemento()),
                String.valueOf(prods.get(i).getCep()),
                String.valueOf(prods.get(i).getTelefone()),
                String.valueOf(prods.get(i).getCidade()),
                 });
        }//fecha for
        
            jtablePessoa.setModel(pe);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Erro! "+e.getMessage());
        }
    }//fecha atualizar
    
    private void deletaP(){
        try {
            int linha = jtablePessoa.getSelectedRow();
            
            if(linha == -1){
                JOptionPane.showMessageDialog(rootPane,"selecione uma linha para exclusão, por favor!");
            }else{
                String id = jtablePessoa.getValueAt(linha, 0).toString();
                
                PessoaServicos ps =servicosFactory.getPessoaServicos();
                ps.deletePessoa(Long.parseLong(id));
                
                JOptionPane.showMessageDialog(rootPane, "Pessoa excluido com sucesso!");
            }//fecha else
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "errou! "+e.getMessage());
        }//fecha cath
    }//fecha deletar
    
    private void procura(){
         try {
            if(jtPesquisarP.getText().isEmpty()){
                atualizar();
            }else{
                String filtro = jComboCli.getSelectedItem().toString();
                String query="";
                if(filtro.equalsIgnoreCase("cod_cli")){
                    query="where cod_cli = "+jtPesquisarP.getText();
                }else if(filtro.equalsIgnoreCase("nome")){
                   query="where nome like '%"+jtPesquisarP.getText()+"%'";     
                }else if(filtro.equalsIgnoreCase("cpf")){
                    query="where cpf like '%"+jtPesquisarP.getText()+"%'";
                }else if(filtro.equalsIgnoreCase("endereco")){
                    query="where endereco like '%"+jtPesquisarP.getText()+"%'";
                }else if(filtro.equalsIgnoreCase("bairro")){
                    query="where bairro like  '%"+jtPesquisarP.getText()+"%'"; 
                }else if(filtro.equalsIgnoreCase("complemento")){
                    query="where complemento like  '%"+jtPesquisarP.getText()+"%'";
                }else if(filtro.equalsIgnoreCase("numero")){
                    query="where numero like '%"+jtPesquisarP.getText()+"%'";
                }else if(filtro.equalsIgnoreCase("cep")){
                    query="where cep like '%"+jtPesquisarP.getText()+"%'";
                }else if(filtro.equalsIgnoreCase("telefone")){
                    query="where telefone like '%"+jtPesquisarP.getText()+"%'";
                }else if(filtro.equalsIgnoreCase("cidade")){
                    query="where cidade like '%"+jtPesquisarP.getText()+"%'";    
                }//fecha else if

                PessoaServicos ps =servicosFactory.getPessoaServicos();
                ArrayList<PessoaVO> pro = new ArrayList<>();
                
                pro = ps.filtrarPessoa(query);//envia a consulta
                
                for (int i = 0; i < pro.size(); i++) {
                    pe.addRow(new String[]{
                        String.valueOf(pro.get(i).getCod_cli()),
                        String.valueOf(pro.get(i).getNome()),
                        String.valueOf(pro.get(i).getCpf()),
                        String.valueOf(pro.get(i).getEndereco()),
                        String.valueOf(pro.get(i).getBairro()),
                        String.valueOf(pro.get(i).getNumero()),
                        String.valueOf(pro.get(i).getComplemento()),
                        String.valueOf(pro.get(i).getCep()),
                        String.valueOf(pro.get(i).getTelefone()),
                        String.valueOf(pro.get(i).getCidade())
                });
            }//fecha for
            
            jtablePessoa.setModel(pe);
    
            }//fecha else
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane,"Erro"+e.getMessage());
        }
    }//fecha procurar
    
    private void limpar(){
        pe.setNumRows(0);
    }//fecha limpar
    
    private void jbLimparTPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparTPActionPerformed
        limpar();
    }//GEN-LAST:event_jbLimparTPActionPerformed

    private void jbPreencherTPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPreencherTPActionPerformed
        limpar();
        atualizar();
    }//GEN-LAST:event_jbPreencherTPActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       deletaP();
        limpar();
        procura();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jtPesquisarPKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtPesquisarPKeyPressed
        limpar();
        procura();
    }//GEN-LAST:event_jtPesquisarPKeyPressed

    private void jtPesquisarPKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtPesquisarPKeyReleased
        limpar();
        procura();
    }//GEN-LAST:event_jtPesquisarPKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboCli;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbLimparTP;
    private javax.swing.JButton jbPreencherTP;
    private javax.swing.JTextField jtPesquisarP;
    private javax.swing.JTable jtablePessoa;
    // End of variables declaration//GEN-END:variables
}
