/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.PessoaVO;
import servicos.PessoaServicos;
import servicos.servicosFactory;

/**
 *
 * @author Fernando & João Vitor
 * @since 12/06/2017
 * @version Beta Xamego 1.9
 */
public class GUIPro extends javax.swing.JInternalFrame {

    /* Criando um modelo de tabela padrão 
     com o nome das colunas */
    DefaultTableModel d = new DefaultTableModel(
            new Object[][]{},
            new Object[]{"Codigo_Produto", "Produto", "Valor", "Quantidade_Estoque"});

    
    /**
     * Creates new form GUIPro
     */
    public GUIPro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlCod_pro = new javax.swing.JLabel();
        jtCod_pro = new javax.swing.JTextField();
        jlProduto = new javax.swing.JLabel();
        jtProduto = new javax.swing.JTextField();
        jlValor = new javax.swing.JLabel();
        jtValor = new javax.swing.JTextField();
        jtQuant_estoque = new javax.swing.JTextField();
        jlQuant_estoque = new javax.swing.JLabel();
        jbLimpar = new javax.swing.JButton();
        jbCadastrar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Cadastro Produto");

        jlCod_pro.setText("Codigo produto:");

        jtCod_pro.setEnabled(false);
        jtCod_pro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtCod_proFocusLost(evt);
            }
        });

        jlProduto.setText("Produto:");

        jtProduto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtProdutoFocusLost(evt);
            }
        });

        jlValor.setText("Valor:");

        jtValor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtValorFocusLost(evt);
            }
        });

        jtQuant_estoque.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtQuant_estoqueFocusLost(evt);
            }
        });

        jlQuant_estoque.setText("Quant. estoque:");

        jbLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/l.fw.png"))); // NOI18N
        jbLimpar.setContentAreaFilled(false);
        jbLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparActionPerformed(evt);
            }
        });

        jbCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/+.fw.png"))); // NOI18N
        jbCadastrar.setContentAreaFilled(false);
        jbCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadastrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jlCod_pro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtCod_pro, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jtProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlProduto)
                    .addComponent(jlValor)
                    .addComponent(jtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtQuant_estoque, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlQuant_estoque, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlCod_pro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtCod_pro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlProduto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlValor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlQuant_estoque, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtQuant_estoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadPro(){
        try {
             PessoaVO proVO = new PessoaVO();
             proVO.setProduto(jtProduto.getText());
             proVO.setValor(Integer.parseInt(jtValor.getText()));
             proVO.setQuantidadeEstoque(Integer.parseInt(jtQuant_estoque.getText()));
            //Enviando o objeto p para o banco de dados
            PessoaServicos ps = servicos.servicosFactory.getPessoaServicos();
            //Chamando o método 
            ps.cadastrarProduto(proVO);
            
            JOptionPane.showMessageDialog(rootPane,"Produto cadastrado com sucesso!");
            
        } catch (Exception e) {JOptionPane.showMessageDialog(rootPane,"Erro! "+e.getMessage(),"erro",JOptionPane.ERROR_MESSAGE);
        }//fecha catch
        
    }//fecha método cadastrar
    private void limpar(){
        jtCod_pro.setText("");
        jtProduto.setText("");
        jtValor.setText("");
        d.setNumRows(0);
    }//fecha método limpar
    
    private void jbLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparActionPerformed
        limpar();
    }//GEN-LAST:event_jbLimparActionPerformed

    private void jbCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadastrarActionPerformed
        cadPro();
    }//GEN-LAST:event_jbCadastrarActionPerformed

    private void jtCod_proFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtCod_proFocusLost
         if(jtCod_pro.getText().isEmpty()){
            jtCod_pro.setBackground(Color.decode("#f98000"));
        }else{
            jtCod_pro.setBackground(Color.white);
            jtCod_pro.setForeground(Color.green);
        }
    }//GEN-LAST:event_jtCod_proFocusLost

    private void jtProdutoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtProdutoFocusLost
         if(jtProduto.getText().isEmpty()){
            jtProduto.setBackground(Color.decode("#f98000"));
        }else{
           jtProduto.setBackground(Color.white);
            jtProduto.setForeground(Color.green);
        }
    }//GEN-LAST:event_jtProdutoFocusLost

    private void jtValorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtValorFocusLost
         if(jtValor.getText().isEmpty()){
            jtValor.setBackground(Color.decode("#f98000"));
        }else{
            jtValor.setBackground(Color.white);
            jtValor.setForeground(Color.green);
        }
    }//GEN-LAST:event_jtValorFocusLost

    private void jtQuant_estoqueFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtQuant_estoqueFocusLost
         if(jtQuant_estoque.getText().isEmpty()){
            jtQuant_estoque.setBackground(Color.decode("#f98000"));
        }else{
            jtQuant_estoque.setBackground(Color.white);
            jtQuant_estoque.setForeground(Color.green);
        }
    }//GEN-LAST:event_jtQuant_estoqueFocusLost

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbCadastrar;
    private javax.swing.JButton jbLimpar;
    private javax.swing.JLabel jlCod_pro;
    private javax.swing.JLabel jlProduto;
    private javax.swing.JLabel jlQuant_estoque;
    private javax.swing.JLabel jlValor;
    private javax.swing.JTextField jtCod_pro;
    private javax.swing.JTextField jtProduto;
    private javax.swing.JTextField jtQuant_estoque;
    private javax.swing.JTextField jtValor;
    // End of variables declaration//GEN-END:variables
}
