/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.Timer;
import java.awt.Image;
import java.awt.Graphics;
import javafx.scene.control.ButtonBar;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Fernando & João Vitor
 * @since 12/06/2017
 * @version Beta Xamego 1.9
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageIcon icon = new ImageIcon(getClass().getResource("/image/s.jpg"));
        Image image = icon.getImage();
        jAreaTrabalho = new javax.swing.JDesktopPane(){
            public void paintComponent(Graphics g){
                g.drawImage(image,0,0,getWidth(),getHeight(),this);
            }
        };
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jbCal = new javax.swing.JButton();
        jbTroca = new javax.swing.JButton();
        jbManuPessoa = new javax.swing.JButton();
        jbManuProduto = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jDataHora = new javax.swing.JPanel();
        jlData = new javax.swing.JLabel();
        jlHora = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jCadastro = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jmiCadPro = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Restaurante");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jInternalFrame1.setVisible(true);
        jInternalFrame1.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbCal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/calcu.fw.png"))); // NOI18N
        jbCal.setBorderPainted(false);
        jbCal.setContentAreaFilled(false);
        jbCal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCalActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(jbCal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 15, 63, -1));

        jbTroca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/usuarios.fw.png"))); // NOI18N
        jbTroca.setContentAreaFilled(false);
        jbTroca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbTrocaActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(jbTroca, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 15, 67, -1));

        jbManuPessoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ma.fw.png"))); // NOI18N
        jbManuPessoa.setContentAreaFilled(false);
        jbManuPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbManuPessoaActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(jbManuPessoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 53, -1));

        jbManuProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/os.fw.png"))); // NOI18N
        jbManuProduto.setContentAreaFilled(false);
        jbManuProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbManuProdutoActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(jbManuProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 15, 97, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/opas.fw.png"))); // NOI18N
        jButton2.setContentAreaFilled(false);
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 73, -1));

        jDataHora.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel1.setText("Create by Fernando & João V.");

        javax.swing.GroupLayout jDataHoraLayout = new javax.swing.GroupLayout(jDataHora);
        jDataHora.setLayout(jDataHoraLayout);
        jDataHoraLayout.setHorizontalGroup(
            jDataHoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDataHoraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlData, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jlHora, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jDataHoraLayout.setVerticalGroup(
            jDataHoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDataHoraLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1))
            .addComponent(jlData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jlHora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jAreaTrabalho.setLayer(jInternalFrame1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jAreaTrabalho.setLayer(jDataHora, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jAreaTrabalhoLayout = new javax.swing.GroupLayout(jAreaTrabalho);
        jAreaTrabalho.setLayout(jAreaTrabalhoLayout);
        jAreaTrabalhoLayout.setHorizontalGroup(
            jAreaTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDataHora, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jAreaTrabalhoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(484, Short.MAX_VALUE))
        );
        jAreaTrabalhoLayout.setVerticalGroup(
            jAreaTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jAreaTrabalhoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 300, Short.MAX_VALUE)
                .addComponent(jDataHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jCadastro.setText("Utilitários");

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/usuarios.fw.png"))); // NOI18N
        jMenuItem1.setText("Cadastro de Pessoa");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jCadastro.add(jMenuItem1);

        jmiCadPro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/os.fw.png"))); // NOI18N
        jmiCadPro.setText("Cadastro de Produto");
        jmiCadPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCadProActionPerformed(evt);
            }
        });
        jCadastro.add(jmiCadPro);

        jMenuBar1.add(jCadastro);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jAreaTrabalho)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jAreaTrabalho)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void abrirCadastro(){
        GUICadPessoa c = new GUICadPessoa();
        jAreaTrabalho.add(c);
        c.setVisible(true);
    }//fecha método
    private void abrirManutencaoP(){
        GUIManutencaoProduto MP = new GUIManutencaoProduto();
        jAreaTrabalho.add(MP);
        MP.setVisible(true);
    }
    
    private void abrirManutencao(){
        GUIManutencaoPessoa m = new GUIManutencaoPessoa();
        jAreaTrabalho.add(m);
        m.setVisible(true);
    }//fecha método
    private void abrirTroca(){
        GUILogin t = new GUILogin();
        jAreaTrabalho.add(t);
        t.setVisible(true);
    }//fecha método
    private void abrirProdutos(){
        GUIPro pro = new GUIPro();
        jAreaTrabalho.add(pro);
        pro.setVisible(true);
    }
    private void abrirGUILogin(){
        GUILogin gl = new GUILogin();
        gl.setVisible(true);
        this.setVisible(false);
    }//fecha abrirGUILogin
    private void abrircal(){
        cal c = new cal();
        c.setVisible(true);
    
    }//fecha abrircal
    private void sair(){
        int op = JOptionPane.showConfirmDialog(rootPane, "Você tem certeza que deseja fechar?");
        if (op==0) System.exit(0);
    }
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
    //data
    Date dataSistema = new Date();
    SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
    jlData.setText(formato.format(dataSistema));
    
    //hora
    Timer timer = new Timer(100,new hora());
    timer.start();
    
    }//GEN-LAST:event_formWindowOpened

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        abrirCadastro();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jbManuPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbManuPessoaActionPerformed
        abrirManutencao();
    }//GEN-LAST:event_jbManuPessoaActionPerformed

    private void jbManuProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbManuProdutoActionPerformed
        abrirManutencaoP();
    }//GEN-LAST:event_jbManuProdutoActionPerformed

    private void jmiCadProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCadProActionPerformed
        abrirProdutos();  
    }//GEN-LAST:event_jmiCadProActionPerformed

    private void jbCalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCalActionPerformed
        abrircal();
    }//GEN-LAST:event_jbCalActionPerformed

    private void jbTrocaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbTrocaActionPerformed
        abrirGUILogin();
    }//GEN-LAST:event_jbTrocaActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        sair();
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            javax.swing.UIManager.setLookAndFeel("com.jtattoo.plaf.hifi.HiFiLookAndFeel");
          /*  for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }*/
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JDesktopPane jAreaTrabalho;
    private javax.swing.JButton jButton2;
    private javax.swing.JMenu jCadastro;
    private javax.swing.JPanel jDataHora;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JButton jbCal;
    private javax.swing.JButton jbManuPessoa;
    private javax.swing.JButton jbManuProduto;
    private javax.swing.JButton jbTroca;
    private javax.swing.JLabel jlData;
    private javax.swing.JLabel jlHora;
    private javax.swing.JMenuItem jmiCadPro;
    // End of variables declaration//GEN-END:variables

    //mostra a hora
class hora implements ActionListener{
@Override
public void actionPerformed(ActionEvent e ){
Calendar now = Calendar.getInstance();
jlHora.setText(String.format("%1$tH:%1$tM:%1$tS",now));
}
} 

}
